# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Ismael\Documents\GitHub\vrxcl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Ismael\Documents\GitHub\vrxcl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Ismael\Documents\GitHub\vrxcl\CMakeFiles C:\Users\Ismael\Documents\GitHub\vrxcl\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Ismael\Documents\GitHub\vrxcl\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gamex86

# Build rule for target.
gamex86: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gamex86
.PHONY : gamex86

# fast build rule for target.
gamex86/fast:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/build
.PHONY : gamex86/fast

Player.obj: Player.c.obj
.PHONY : Player.obj

# target to build an object file
Player.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Player.c.obj
.PHONY : Player.c.obj

Player.i: Player.c.i
.PHONY : Player.i

# target to preprocess a source file
Player.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Player.c.i
.PHONY : Player.c.i

Player.s: Player.c.s
.PHONY : Player.s

# target to generate assembly for a file
Player.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Player.c.s
.PHONY : Player.c.s

Spirit.obj: Spirit.c.obj
.PHONY : Spirit.obj

# target to build an object file
Spirit.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Spirit.c.obj
.PHONY : Spirit.c.obj

Spirit.i: Spirit.c.i
.PHONY : Spirit.i

# target to preprocess a source file
Spirit.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Spirit.c.i
.PHONY : Spirit.c.i

Spirit.s: Spirit.c.s
.PHONY : Spirit.s

# target to generate assembly for a file
Spirit.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Spirit.c.s
.PHONY : Spirit.c.s

Talents.obj: Talents.c.obj
.PHONY : Talents.obj

# target to build an object file
Talents.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Talents.c.obj
.PHONY : Talents.c.obj

Talents.i: Talents.c.i
.PHONY : Talents.i

# target to preprocess a source file
Talents.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Talents.c.i
.PHONY : Talents.c.i

Talents.s: Talents.c.s
.PHONY : Talents.s

# target to generate assembly for a file
Talents.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/Talents.c.s
.PHONY : Talents.c.s

ai/AStar.obj: ai/AStar.c.obj
.PHONY : ai/AStar.obj

# target to build an object file
ai/AStar.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/AStar.c.obj
.PHONY : ai/AStar.c.obj

ai/AStar.i: ai/AStar.c.i
.PHONY : ai/AStar.i

# target to preprocess a source file
ai/AStar.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/AStar.c.i
.PHONY : ai/AStar.c.i

ai/AStar.s: ai/AStar.c.s
.PHONY : ai/AStar.s

# target to generate assembly for a file
ai/AStar.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/AStar.c.s
.PHONY : ai/AStar.c.s

ai/ai_class_dmbot.obj: ai/ai_class_dmbot.c.obj
.PHONY : ai/ai_class_dmbot.obj

# target to build an object file
ai/ai_class_dmbot.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_class_dmbot.c.obj
.PHONY : ai/ai_class_dmbot.c.obj

ai/ai_class_dmbot.i: ai/ai_class_dmbot.c.i
.PHONY : ai/ai_class_dmbot.i

# target to preprocess a source file
ai/ai_class_dmbot.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_class_dmbot.c.i
.PHONY : ai/ai_class_dmbot.c.i

ai/ai_class_dmbot.s: ai/ai_class_dmbot.c.s
.PHONY : ai/ai_class_dmbot.s

# target to generate assembly for a file
ai/ai_class_dmbot.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_class_dmbot.c.s
.PHONY : ai/ai_class_dmbot.c.s

ai/ai_class_monster_default.obj: ai/ai_class_monster_default.c.obj
.PHONY : ai/ai_class_monster_default.obj

# target to build an object file
ai/ai_class_monster_default.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_class_monster_default.c.obj
.PHONY : ai/ai_class_monster_default.c.obj

ai/ai_class_monster_default.i: ai/ai_class_monster_default.c.i
.PHONY : ai/ai_class_monster_default.i

# target to preprocess a source file
ai/ai_class_monster_default.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_class_monster_default.c.i
.PHONY : ai/ai_class_monster_default.c.i

ai/ai_class_monster_default.s: ai/ai_class_monster_default.c.s
.PHONY : ai/ai_class_monster_default.s

# target to generate assembly for a file
ai/ai_class_monster_default.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_class_monster_default.c.s
.PHONY : ai/ai_class_monster_default.c.s

ai/ai_dropnodes.obj: ai/ai_dropnodes.c.obj
.PHONY : ai/ai_dropnodes.obj

# target to build an object file
ai/ai_dropnodes.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_dropnodes.c.obj
.PHONY : ai/ai_dropnodes.c.obj

ai/ai_dropnodes.i: ai/ai_dropnodes.c.i
.PHONY : ai/ai_dropnodes.i

# target to preprocess a source file
ai/ai_dropnodes.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_dropnodes.c.i
.PHONY : ai/ai_dropnodes.c.i

ai/ai_dropnodes.s: ai/ai_dropnodes.c.s
.PHONY : ai/ai_dropnodes.s

# target to generate assembly for a file
ai/ai_dropnodes.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_dropnodes.c.s
.PHONY : ai/ai_dropnodes.c.s

ai/ai_items.obj: ai/ai_items.c.obj
.PHONY : ai/ai_items.obj

# target to build an object file
ai/ai_items.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_items.c.obj
.PHONY : ai/ai_items.c.obj

ai/ai_items.i: ai/ai_items.c.i
.PHONY : ai/ai_items.i

# target to preprocess a source file
ai/ai_items.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_items.c.i
.PHONY : ai/ai_items.c.i

ai/ai_items.s: ai/ai_items.c.s
.PHONY : ai/ai_items.s

# target to generate assembly for a file
ai/ai_items.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_items.c.s
.PHONY : ai/ai_items.c.s

ai/ai_links.obj: ai/ai_links.c.obj
.PHONY : ai/ai_links.obj

# target to build an object file
ai/ai_links.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_links.c.obj
.PHONY : ai/ai_links.c.obj

ai/ai_links.i: ai/ai_links.c.i
.PHONY : ai/ai_links.i

# target to preprocess a source file
ai/ai_links.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_links.c.i
.PHONY : ai/ai_links.c.i

ai/ai_links.s: ai/ai_links.c.s
.PHONY : ai/ai_links.s

# target to generate assembly for a file
ai/ai_links.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_links.c.s
.PHONY : ai/ai_links.c.s

ai/ai_main.obj: ai/ai_main.c.obj
.PHONY : ai/ai_main.obj

# target to build an object file
ai/ai_main.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_main.c.obj
.PHONY : ai/ai_main.c.obj

ai/ai_main.i: ai/ai_main.c.i
.PHONY : ai/ai_main.i

# target to preprocess a source file
ai/ai_main.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_main.c.i
.PHONY : ai/ai_main.c.i

ai/ai_main.s: ai/ai_main.c.s
.PHONY : ai/ai_main.s

# target to generate assembly for a file
ai/ai_main.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_main.c.s
.PHONY : ai/ai_main.c.s

ai/ai_movement.obj: ai/ai_movement.c.obj
.PHONY : ai/ai_movement.obj

# target to build an object file
ai/ai_movement.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_movement.c.obj
.PHONY : ai/ai_movement.c.obj

ai/ai_movement.i: ai/ai_movement.c.i
.PHONY : ai/ai_movement.i

# target to preprocess a source file
ai/ai_movement.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_movement.c.i
.PHONY : ai/ai_movement.c.i

ai/ai_movement.s: ai/ai_movement.c.s
.PHONY : ai/ai_movement.s

# target to generate assembly for a file
ai/ai_movement.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_movement.c.s
.PHONY : ai/ai_movement.c.s

ai/ai_navigation.obj: ai/ai_navigation.c.obj
.PHONY : ai/ai_navigation.obj

# target to build an object file
ai/ai_navigation.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_navigation.c.obj
.PHONY : ai/ai_navigation.c.obj

ai/ai_navigation.i: ai/ai_navigation.c.i
.PHONY : ai/ai_navigation.i

# target to preprocess a source file
ai/ai_navigation.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_navigation.c.i
.PHONY : ai/ai_navigation.c.i

ai/ai_navigation.s: ai/ai_navigation.c.s
.PHONY : ai/ai_navigation.s

# target to generate assembly for a file
ai/ai_navigation.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_navigation.c.s
.PHONY : ai/ai_navigation.c.s

ai/ai_nodes.obj: ai/ai_nodes.c.obj
.PHONY : ai/ai_nodes.obj

# target to build an object file
ai/ai_nodes.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_nodes.c.obj
.PHONY : ai/ai_nodes.c.obj

ai/ai_nodes.i: ai/ai_nodes.c.i
.PHONY : ai/ai_nodes.i

# target to preprocess a source file
ai/ai_nodes.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_nodes.c.i
.PHONY : ai/ai_nodes.c.i

ai/ai_nodes.s: ai/ai_nodes.c.s
.PHONY : ai/ai_nodes.s

# target to generate assembly for a file
ai/ai_nodes.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_nodes.c.s
.PHONY : ai/ai_nodes.c.s

ai/ai_tools.obj: ai/ai_tools.c.obj
.PHONY : ai/ai_tools.obj

# target to build an object file
ai/ai_tools.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_tools.c.obj
.PHONY : ai/ai_tools.c.obj

ai/ai_tools.i: ai/ai_tools.c.i
.PHONY : ai/ai_tools.i

# target to preprocess a source file
ai/ai_tools.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_tools.c.i
.PHONY : ai/ai_tools.c.i

ai/ai_tools.s: ai/ai_tools.c.s
.PHONY : ai/ai_tools.s

# target to generate assembly for a file
ai/ai_tools.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_tools.c.s
.PHONY : ai/ai_tools.c.s

ai/ai_weapons.obj: ai/ai_weapons.c.obj
.PHONY : ai/ai_weapons.obj

# target to build an object file
ai/ai_weapons.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_weapons.c.obj
.PHONY : ai/ai_weapons.c.obj

ai/ai_weapons.i: ai/ai_weapons.c.i
.PHONY : ai/ai_weapons.i

# target to preprocess a source file
ai/ai_weapons.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_weapons.c.i
.PHONY : ai/ai_weapons.c.i

ai/ai_weapons.s: ai/ai_weapons.c.s
.PHONY : ai/ai_weapons.s

# target to generate assembly for a file
ai/ai_weapons.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/ai_weapons.c.s
.PHONY : ai/ai_weapons.c.s

ai/bot_common.obj: ai/bot_common.c.obj
.PHONY : ai/bot_common.obj

# target to build an object file
ai/bot_common.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/bot_common.c.obj
.PHONY : ai/bot_common.c.obj

ai/bot_common.i: ai/bot_common.c.i
.PHONY : ai/bot_common.i

# target to preprocess a source file
ai/bot_common.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/bot_common.c.i
.PHONY : ai/bot_common.c.i

ai/bot_common.s: ai/bot_common.c.s
.PHONY : ai/bot_common.s

# target to generate assembly for a file
ai/bot_common.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/bot_common.c.s
.PHONY : ai/bot_common.c.s

ai/bot_spawn.obj: ai/bot_spawn.c.obj
.PHONY : ai/bot_spawn.obj

# target to build an object file
ai/bot_spawn.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/bot_spawn.c.obj
.PHONY : ai/bot_spawn.c.obj

ai/bot_spawn.i: ai/bot_spawn.c.i
.PHONY : ai/bot_spawn.i

# target to preprocess a source file
ai/bot_spawn.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/bot_spawn.c.i
.PHONY : ai/bot_spawn.c.i

ai/bot_spawn.s: ai/bot_spawn.c.s
.PHONY : ai/bot_spawn.s

# target to generate assembly for a file
ai/bot_spawn.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ai/bot_spawn.c.s
.PHONY : ai/bot_spawn.c.s

ally.obj: ally.c.obj
.PHONY : ally.obj

# target to build an object file
ally.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ally.c.obj
.PHONY : ally.c.obj

ally.i: ally.c.i
.PHONY : ally.i

# target to preprocess a source file
ally.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ally.c.i
.PHONY : ally.c.i

ally.s: ally.c.s
.PHONY : ally.s

# target to generate assembly for a file
ally.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ally.c.s
.PHONY : ally.c.s

armory.obj: armory.c.obj
.PHONY : armory.obj

# target to build an object file
armory.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/armory.c.obj
.PHONY : armory.c.obj

armory.i: armory.c.i
.PHONY : armory.i

# target to preprocess a source file
armory.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/armory.c.i
.PHONY : armory.c.i

armory.s: armory.c.s
.PHONY : armory.s

# target to generate assembly for a file
armory.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/armory.c.s
.PHONY : armory.c.s

auras.obj: auras.c.obj
.PHONY : auras.obj

# target to build an object file
auras.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/auras.c.obj
.PHONY : auras.c.obj

auras.i: auras.c.i
.PHONY : auras.i

# target to preprocess a source file
auras.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/auras.c.i
.PHONY : auras.c.i

auras.s: auras.c.s
.PHONY : auras.s

# target to generate assembly for a file
auras.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/auras.c.s
.PHONY : auras.c.s

backpack.obj: backpack.c.obj
.PHONY : backpack.obj

# target to build an object file
backpack.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/backpack.c.obj
.PHONY : backpack.c.obj

backpack.i: backpack.c.i
.PHONY : backpack.i

# target to preprocess a source file
backpack.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/backpack.c.i
.PHONY : backpack.c.i

backpack.s: backpack.c.s
.PHONY : backpack.s

# target to generate assembly for a file
backpack.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/backpack.c.s
.PHONY : backpack.c.s

bombspell.obj: bombspell.c.obj
.PHONY : bombspell.obj

# target to build an object file
bombspell.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/bombspell.c.obj
.PHONY : bombspell.c.obj

bombspell.i: bombspell.c.i
.PHONY : bombspell.i

# target to preprocess a source file
bombspell.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/bombspell.c.i
.PHONY : bombspell.c.i

bombspell.s: bombspell.c.s
.PHONY : bombspell.s

# target to generate assembly for a file
bombspell.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/bombspell.c.s
.PHONY : bombspell.c.s

boss_general.obj: boss_general.c.obj
.PHONY : boss_general.obj

# target to build an object file
boss_general.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_general.c.obj
.PHONY : boss_general.c.obj

boss_general.i: boss_general.c.i
.PHONY : boss_general.i

# target to preprocess a source file
boss_general.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_general.c.i
.PHONY : boss_general.c.i

boss_general.s: boss_general.c.s
.PHONY : boss_general.s

# target to generate assembly for a file
boss_general.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_general.c.s
.PHONY : boss_general.c.s

boss_makron.obj: boss_makron.c.obj
.PHONY : boss_makron.obj

# target to build an object file
boss_makron.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_makron.c.obj
.PHONY : boss_makron.c.obj

boss_makron.i: boss_makron.c.i
.PHONY : boss_makron.i

# target to preprocess a source file
boss_makron.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_makron.c.i
.PHONY : boss_makron.c.i

boss_makron.s: boss_makron.c.s
.PHONY : boss_makron.s

# target to generate assembly for a file
boss_makron.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_makron.c.s
.PHONY : boss_makron.c.s

boss_tank.obj: boss_tank.c.obj
.PHONY : boss_tank.obj

# target to build an object file
boss_tank.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_tank.c.obj
.PHONY : boss_tank.c.obj

boss_tank.i: boss_tank.c.i
.PHONY : boss_tank.i

# target to preprocess a source file
boss_tank.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_tank.c.i
.PHONY : boss_tank.c.i

boss_tank.s: boss_tank.c.s
.PHONY : boss_tank.s

# target to generate assembly for a file
boss_tank.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/boss_tank.c.s
.PHONY : boss_tank.c.s

class_brain.obj: class_brain.c.obj
.PHONY : class_brain.obj

# target to build an object file
class_brain.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/class_brain.c.obj
.PHONY : class_brain.c.obj

class_brain.i: class_brain.c.i
.PHONY : class_brain.i

# target to preprocess a source file
class_brain.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/class_brain.c.i
.PHONY : class_brain.c.i

class_brain.s: class_brain.c.s
.PHONY : class_brain.s

# target to generate assembly for a file
class_brain.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/class_brain.c.s
.PHONY : class_brain.c.s

class_demon.obj: class_demon.c.obj
.PHONY : class_demon.obj

# target to build an object file
class_demon.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/class_demon.c.obj
.PHONY : class_demon.c.obj

class_demon.i: class_demon.c.i
.PHONY : class_demon.i

# target to preprocess a source file
class_demon.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/class_demon.c.i
.PHONY : class_demon.c.i

class_demon.s: class_demon.c.s
.PHONY : class_demon.s

# target to generate assembly for a file
class_demon.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/class_demon.c.s
.PHONY : class_demon.c.s

cloak.obj: cloak.c.obj
.PHONY : cloak.obj

# target to build an object file
cloak.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/cloak.c.obj
.PHONY : cloak.c.obj

cloak.i: cloak.c.i
.PHONY : cloak.i

# target to preprocess a source file
cloak.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/cloak.c.i
.PHONY : cloak.c.i

cloak.s: cloak.c.s
.PHONY : cloak.s

# target to generate assembly for a file
cloak.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/cloak.c.s
.PHONY : cloak.c.s

ctf.obj: ctf.c.obj
.PHONY : ctf.obj

# target to build an object file
ctf.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ctf.c.obj
.PHONY : ctf.c.obj

ctf.i: ctf.c.i
.PHONY : ctf.i

# target to preprocess a source file
ctf.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ctf.c.i
.PHONY : ctf.c.i

ctf.s: ctf.c.s
.PHONY : ctf.s

# target to generate assembly for a file
ctf.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ctf.c.s
.PHONY : ctf.c.s

damage.obj: damage.c.obj
.PHONY : damage.obj

# target to build an object file
damage.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/damage.c.obj
.PHONY : damage.c.obj

damage.i: damage.c.i
.PHONY : damage.i

# target to preprocess a source file
damage.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/damage.c.i
.PHONY : damage.c.i

damage.s: damage.c.s
.PHONY : damage.s

# target to generate assembly for a file
damage.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/damage.c.s
.PHONY : damage.c.s

domination.obj: domination.c.obj
.PHONY : domination.obj

# target to build an object file
domination.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/domination.c.obj
.PHONY : domination.c.obj

domination.i: domination.c.i
.PHONY : domination.i

# target to preprocess a source file
domination.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/domination.c.i
.PHONY : domination.c.i

domination.s: domination.c.s
.PHONY : domination.s

# target to generate assembly for a file
domination.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/domination.c.s
.PHONY : domination.c.s

drone_ai.obj: drone_ai.c.obj
.PHONY : drone_ai.obj

# target to build an object file
drone_ai.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_ai.c.obj
.PHONY : drone_ai.c.obj

drone_ai.i: drone_ai.c.i
.PHONY : drone_ai.i

# target to preprocess a source file
drone_ai.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_ai.c.i
.PHONY : drone_ai.c.i

drone_ai.s: drone_ai.c.s
.PHONY : drone_ai.s

# target to generate assembly for a file
drone_ai.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_ai.c.s
.PHONY : drone_ai.c.s

drone_berserk.obj: drone_berserk.c.obj
.PHONY : drone_berserk.obj

# target to build an object file
drone_berserk.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_berserk.c.obj
.PHONY : drone_berserk.c.obj

drone_berserk.i: drone_berserk.c.i
.PHONY : drone_berserk.i

# target to preprocess a source file
drone_berserk.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_berserk.c.i
.PHONY : drone_berserk.c.i

drone_berserk.s: drone_berserk.c.s
.PHONY : drone_berserk.s

# target to generate assembly for a file
drone_berserk.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_berserk.c.s
.PHONY : drone_berserk.c.s

drone_bitch.obj: drone_bitch.c.obj
.PHONY : drone_bitch.obj

# target to build an object file
drone_bitch.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_bitch.c.obj
.PHONY : drone_bitch.c.obj

drone_bitch.i: drone_bitch.c.i
.PHONY : drone_bitch.i

# target to preprocess a source file
drone_bitch.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_bitch.c.i
.PHONY : drone_bitch.c.i

drone_bitch.s: drone_bitch.c.s
.PHONY : drone_bitch.s

# target to generate assembly for a file
drone_bitch.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_bitch.c.s
.PHONY : drone_bitch.c.s

drone_brain.obj: drone_brain.c.obj
.PHONY : drone_brain.obj

# target to build an object file
drone_brain.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_brain.c.obj
.PHONY : drone_brain.c.obj

drone_brain.i: drone_brain.c.i
.PHONY : drone_brain.i

# target to preprocess a source file
drone_brain.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_brain.c.i
.PHONY : drone_brain.c.i

drone_brain.s: drone_brain.c.s
.PHONY : drone_brain.s

# target to generate assembly for a file
drone_brain.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_brain.c.s
.PHONY : drone_brain.c.s

drone_decoy.obj: drone_decoy.c.obj
.PHONY : drone_decoy.obj

# target to build an object file
drone_decoy.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_decoy.c.obj
.PHONY : drone_decoy.c.obj

drone_decoy.i: drone_decoy.c.i
.PHONY : drone_decoy.i

# target to preprocess a source file
drone_decoy.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_decoy.c.i
.PHONY : drone_decoy.c.i

drone_decoy.s: drone_decoy.c.s
.PHONY : drone_decoy.s

# target to generate assembly for a file
drone_decoy.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_decoy.c.s
.PHONY : drone_decoy.c.s

drone_gladiator.obj: drone_gladiator.c.obj
.PHONY : drone_gladiator.obj

# target to build an object file
drone_gladiator.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_gladiator.c.obj
.PHONY : drone_gladiator.c.obj

drone_gladiator.i: drone_gladiator.c.i
.PHONY : drone_gladiator.i

# target to preprocess a source file
drone_gladiator.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_gladiator.c.i
.PHONY : drone_gladiator.c.i

drone_gladiator.s: drone_gladiator.c.s
.PHONY : drone_gladiator.s

# target to generate assembly for a file
drone_gladiator.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_gladiator.c.s
.PHONY : drone_gladiator.c.s

drone_gunner.obj: drone_gunner.c.obj
.PHONY : drone_gunner.obj

# target to build an object file
drone_gunner.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_gunner.c.obj
.PHONY : drone_gunner.c.obj

drone_gunner.i: drone_gunner.c.i
.PHONY : drone_gunner.i

# target to preprocess a source file
drone_gunner.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_gunner.c.i
.PHONY : drone_gunner.c.i

drone_gunner.s: drone_gunner.c.s
.PHONY : drone_gunner.s

# target to generate assembly for a file
drone_gunner.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_gunner.c.s
.PHONY : drone_gunner.c.s

drone_infantry.obj: drone_infantry.c.obj
.PHONY : drone_infantry.obj

# target to build an object file
drone_infantry.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_infantry.c.obj
.PHONY : drone_infantry.c.obj

drone_infantry.i: drone_infantry.c.i
.PHONY : drone_infantry.i

# target to preprocess a source file
drone_infantry.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_infantry.c.i
.PHONY : drone_infantry.c.i

drone_infantry.s: drone_infantry.c.s
.PHONY : drone_infantry.s

# target to generate assembly for a file
drone_infantry.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_infantry.c.s
.PHONY : drone_infantry.c.s

drone_jorg.obj: drone_jorg.c.obj
.PHONY : drone_jorg.obj

# target to build an object file
drone_jorg.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_jorg.c.obj
.PHONY : drone_jorg.c.obj

drone_jorg.i: drone_jorg.c.i
.PHONY : drone_jorg.i

# target to preprocess a source file
drone_jorg.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_jorg.c.i
.PHONY : drone_jorg.c.i

drone_jorg.s: drone_jorg.c.s
.PHONY : drone_jorg.s

# target to generate assembly for a file
drone_jorg.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_jorg.c.s
.PHONY : drone_jorg.c.s

drone_makron.obj: drone_makron.c.obj
.PHONY : drone_makron.obj

# target to build an object file
drone_makron.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_makron.c.obj
.PHONY : drone_makron.c.obj

drone_makron.i: drone_makron.c.i
.PHONY : drone_makron.i

# target to preprocess a source file
drone_makron.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_makron.c.i
.PHONY : drone_makron.c.i

drone_makron.s: drone_makron.c.s
.PHONY : drone_makron.s

# target to generate assembly for a file
drone_makron.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_makron.c.s
.PHONY : drone_makron.c.s

drone_medic.obj: drone_medic.c.obj
.PHONY : drone_medic.obj

# target to build an object file
drone_medic.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_medic.c.obj
.PHONY : drone_medic.c.obj

drone_medic.i: drone_medic.c.i
.PHONY : drone_medic.i

# target to preprocess a source file
drone_medic.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_medic.c.i
.PHONY : drone_medic.c.i

drone_medic.s: drone_medic.c.s
.PHONY : drone_medic.s

# target to generate assembly for a file
drone_medic.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_medic.c.s
.PHONY : drone_medic.c.s

drone_misc.obj: drone_misc.c.obj
.PHONY : drone_misc.obj

# target to build an object file
drone_misc.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_misc.c.obj
.PHONY : drone_misc.c.obj

drone_misc.i: drone_misc.c.i
.PHONY : drone_misc.i

# target to preprocess a source file
drone_misc.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_misc.c.i
.PHONY : drone_misc.c.i

drone_misc.s: drone_misc.c.s
.PHONY : drone_misc.s

# target to generate assembly for a file
drone_misc.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_misc.c.s
.PHONY : drone_misc.c.s

drone_move.obj: drone_move.c.obj
.PHONY : drone_move.obj

# target to build an object file
drone_move.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_move.c.obj
.PHONY : drone_move.c.obj

drone_move.i: drone_move.c.i
.PHONY : drone_move.i

# target to preprocess a source file
drone_move.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_move.c.i
.PHONY : drone_move.c.i

drone_move.s: drone_move.c.s
.PHONY : drone_move.s

# target to generate assembly for a file
drone_move.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_move.c.s
.PHONY : drone_move.c.s

drone_mutant.obj: drone_mutant.c.obj
.PHONY : drone_mutant.obj

# target to build an object file
drone_mutant.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_mutant.c.obj
.PHONY : drone_mutant.c.obj

drone_mutant.i: drone_mutant.c.i
.PHONY : drone_mutant.i

# target to preprocess a source file
drone_mutant.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_mutant.c.i
.PHONY : drone_mutant.c.i

drone_mutant.s: drone_mutant.c.s
.PHONY : drone_mutant.s

# target to generate assembly for a file
drone_mutant.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_mutant.c.s
.PHONY : drone_mutant.c.s

drone_parasite.obj: drone_parasite.c.obj
.PHONY : drone_parasite.obj

# target to build an object file
drone_parasite.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_parasite.c.obj
.PHONY : drone_parasite.c.obj

drone_parasite.i: drone_parasite.c.i
.PHONY : drone_parasite.i

# target to preprocess a source file
drone_parasite.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_parasite.c.i
.PHONY : drone_parasite.c.i

drone_parasite.s: drone_parasite.c.s
.PHONY : drone_parasite.s

# target to generate assembly for a file
drone_parasite.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_parasite.c.s
.PHONY : drone_parasite.c.s

drone_retard.obj: drone_retard.c.obj
.PHONY : drone_retard.obj

# target to build an object file
drone_retard.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_retard.c.obj
.PHONY : drone_retard.c.obj

drone_retard.i: drone_retard.c.i
.PHONY : drone_retard.i

# target to preprocess a source file
drone_retard.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_retard.c.i
.PHONY : drone_retard.c.i

drone_retard.s: drone_retard.c.s
.PHONY : drone_retard.s

# target to generate assembly for a file
drone_retard.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_retard.c.s
.PHONY : drone_retard.c.s

drone_soldier.obj: drone_soldier.c.obj
.PHONY : drone_soldier.obj

# target to build an object file
drone_soldier.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_soldier.c.obj
.PHONY : drone_soldier.c.obj

drone_soldier.i: drone_soldier.c.i
.PHONY : drone_soldier.i

# target to preprocess a source file
drone_soldier.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_soldier.c.i
.PHONY : drone_soldier.c.i

drone_soldier.s: drone_soldier.c.s
.PHONY : drone_soldier.s

# target to generate assembly for a file
drone_soldier.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_soldier.c.s
.PHONY : drone_soldier.c.s

drone_supertank.obj: drone_supertank.c.obj
.PHONY : drone_supertank.obj

# target to build an object file
drone_supertank.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_supertank.c.obj
.PHONY : drone_supertank.c.obj

drone_supertank.i: drone_supertank.c.i
.PHONY : drone_supertank.i

# target to preprocess a source file
drone_supertank.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_supertank.c.i
.PHONY : drone_supertank.c.i

drone_supertank.s: drone_supertank.c.s
.PHONY : drone_supertank.s

# target to generate assembly for a file
drone_supertank.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_supertank.c.s
.PHONY : drone_supertank.c.s

drone_tank.obj: drone_tank.c.obj
.PHONY : drone_tank.obj

# target to build an object file
drone_tank.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_tank.c.obj
.PHONY : drone_tank.c.obj

drone_tank.i: drone_tank.c.i
.PHONY : drone_tank.i

# target to preprocess a source file
drone_tank.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_tank.c.i
.PHONY : drone_tank.c.i

drone_tank.s: drone_tank.c.s
.PHONY : drone_tank.s

# target to generate assembly for a file
drone_tank.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/drone_tank.c.s
.PHONY : drone_tank.c.s

ents.obj: ents.c.obj
.PHONY : ents.obj

# target to build an object file
ents.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ents.c.obj
.PHONY : ents.c.obj

ents.i: ents.c.i
.PHONY : ents.i

# target to preprocess a source file
ents.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ents.c.i
.PHONY : ents.c.i

ents.s: ents.c.s
.PHONY : ents.s

# target to generate assembly for a file
ents.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/ents.c.s
.PHONY : ents.c.s

file_output.obj: file_output.c.obj
.PHONY : file_output.obj

# target to build an object file
file_output.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/file_output.c.obj
.PHONY : file_output.c.obj

file_output.i: file_output.c.i
.PHONY : file_output.i

# target to preprocess a source file
file_output.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/file_output.c.i
.PHONY : file_output.c.i

file_output.s: file_output.c.s
.PHONY : file_output.s

# target to generate assembly for a file
file_output.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/file_output.c.s
.PHONY : file_output.c.s

flying_skull.obj: flying_skull.c.obj
.PHONY : flying_skull.obj

# target to build an object file
flying_skull.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/flying_skull.c.obj
.PHONY : flying_skull.c.obj

flying_skull.i: flying_skull.c.i
.PHONY : flying_skull.i

# target to preprocess a source file
flying_skull.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/flying_skull.c.i
.PHONY : flying_skull.c.i

flying_skull.s: flying_skull.c.s
.PHONY : flying_skull.s

# target to generate assembly for a file
flying_skull.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/flying_skull.c.s
.PHONY : flying_skull.c.s

forcewall.obj: forcewall.c.obj
.PHONY : forcewall.obj

# target to build an object file
forcewall.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/forcewall.c.obj
.PHONY : forcewall.c.obj

forcewall.i: forcewall.c.i
.PHONY : forcewall.i

# target to preprocess a source file
forcewall.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/forcewall.c.i
.PHONY : forcewall.c.i

forcewall.s: forcewall.c.s
.PHONY : forcewall.s

# target to generate assembly for a file
forcewall.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/forcewall.c.s
.PHONY : forcewall.c.s

g_chase.obj: g_chase.c.obj
.PHONY : g_chase.obj

# target to build an object file
g_chase.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_chase.c.obj
.PHONY : g_chase.c.obj

g_chase.i: g_chase.c.i
.PHONY : g_chase.i

# target to preprocess a source file
g_chase.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_chase.c.i
.PHONY : g_chase.c.i

g_chase.s: g_chase.c.s
.PHONY : g_chase.s

# target to generate assembly for a file
g_chase.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_chase.c.s
.PHONY : g_chase.c.s

g_cmds.obj: g_cmds.c.obj
.PHONY : g_cmds.obj

# target to build an object file
g_cmds.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_cmds.c.obj
.PHONY : g_cmds.c.obj

g_cmds.i: g_cmds.c.i
.PHONY : g_cmds.i

# target to preprocess a source file
g_cmds.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_cmds.c.i
.PHONY : g_cmds.c.i

g_cmds.s: g_cmds.c.s
.PHONY : g_cmds.s

# target to generate assembly for a file
g_cmds.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_cmds.c.s
.PHONY : g_cmds.c.s

g_combat.obj: g_combat.c.obj
.PHONY : g_combat.obj

# target to build an object file
g_combat.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_combat.c.obj
.PHONY : g_combat.c.obj

g_combat.i: g_combat.c.i
.PHONY : g_combat.i

# target to preprocess a source file
g_combat.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_combat.c.i
.PHONY : g_combat.c.i

g_combat.s: g_combat.c.s
.PHONY : g_combat.s

# target to generate assembly for a file
g_combat.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_combat.c.s
.PHONY : g_combat.c.s

g_flame.obj: g_flame.c.obj
.PHONY : g_flame.obj

# target to build an object file
g_flame.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_flame.c.obj
.PHONY : g_flame.c.obj

g_flame.i: g_flame.c.i
.PHONY : g_flame.i

# target to preprocess a source file
g_flame.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_flame.c.i
.PHONY : g_flame.c.i

g_flame.s: g_flame.c.s
.PHONY : g_flame.s

# target to generate assembly for a file
g_flame.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_flame.c.s
.PHONY : g_flame.c.s

g_func.obj: g_func.c.obj
.PHONY : g_func.obj

# target to build an object file
g_func.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_func.c.obj
.PHONY : g_func.c.obj

g_func.i: g_func.c.i
.PHONY : g_func.i

# target to preprocess a source file
g_func.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_func.c.i
.PHONY : g_func.c.i

g_func.s: g_func.c.s
.PHONY : g_func.s

# target to generate assembly for a file
g_func.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_func.c.s
.PHONY : g_func.c.s

g_items.obj: g_items.c.obj
.PHONY : g_items.obj

# target to build an object file
g_items.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_items.c.obj
.PHONY : g_items.c.obj

g_items.i: g_items.c.i
.PHONY : g_items.i

# target to preprocess a source file
g_items.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_items.c.i
.PHONY : g_items.c.i

g_items.s: g_items.c.s
.PHONY : g_items.s

# target to generate assembly for a file
g_items.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_items.c.s
.PHONY : g_items.c.s

g_lasers.obj: g_lasers.c.obj
.PHONY : g_lasers.obj

# target to build an object file
g_lasers.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_lasers.c.obj
.PHONY : g_lasers.c.obj

g_lasers.i: g_lasers.c.i
.PHONY : g_lasers.i

# target to preprocess a source file
g_lasers.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_lasers.c.i
.PHONY : g_lasers.c.i

g_lasers.s: g_lasers.c.s
.PHONY : g_lasers.s

# target to generate assembly for a file
g_lasers.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_lasers.c.s
.PHONY : g_lasers.c.s

g_main.obj: g_main.c.obj
.PHONY : g_main.obj

# target to build an object file
g_main.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_main.c.obj
.PHONY : g_main.c.obj

g_main.i: g_main.c.i
.PHONY : g_main.i

# target to preprocess a source file
g_main.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_main.c.i
.PHONY : g_main.c.i

g_main.s: g_main.c.s
.PHONY : g_main.s

# target to generate assembly for a file
g_main.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_main.c.s
.PHONY : g_main.c.s

g_misc.obj: g_misc.c.obj
.PHONY : g_misc.obj

# target to build an object file
g_misc.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_misc.c.obj
.PHONY : g_misc.c.obj

g_misc.i: g_misc.c.i
.PHONY : g_misc.i

# target to preprocess a source file
g_misc.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_misc.c.i
.PHONY : g_misc.c.i

g_misc.s: g_misc.c.s
.PHONY : g_misc.s

# target to generate assembly for a file
g_misc.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_misc.c.s
.PHONY : g_misc.c.s

g_monster.obj: g_monster.c.obj
.PHONY : g_monster.obj

# target to build an object file
g_monster.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_monster.c.obj
.PHONY : g_monster.c.obj

g_monster.i: g_monster.c.i
.PHONY : g_monster.i

# target to preprocess a source file
g_monster.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_monster.c.i
.PHONY : g_monster.c.i

g_monster.s: g_monster.c.s
.PHONY : g_monster.s

# target to generate assembly for a file
g_monster.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_monster.c.s
.PHONY : g_monster.c.s

g_phys.obj: g_phys.c.obj
.PHONY : g_phys.obj

# target to build an object file
g_phys.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_phys.c.obj
.PHONY : g_phys.c.obj

g_phys.i: g_phys.c.i
.PHONY : g_phys.i

# target to preprocess a source file
g_phys.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_phys.c.i
.PHONY : g_phys.c.i

g_phys.s: g_phys.c.s
.PHONY : g_phys.s

# target to generate assembly for a file
g_phys.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_phys.c.s
.PHONY : g_phys.c.s

g_save.obj: g_save.c.obj
.PHONY : g_save.obj

# target to build an object file
g_save.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_save.c.obj
.PHONY : g_save.c.obj

g_save.i: g_save.c.i
.PHONY : g_save.i

# target to preprocess a source file
g_save.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_save.c.i
.PHONY : g_save.c.i

g_save.s: g_save.c.s
.PHONY : g_save.s

# target to generate assembly for a file
g_save.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_save.c.s
.PHONY : g_save.c.s

g_spawn.obj: g_spawn.c.obj
.PHONY : g_spawn.obj

# target to build an object file
g_spawn.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_spawn.c.obj
.PHONY : g_spawn.c.obj

g_spawn.i: g_spawn.c.i
.PHONY : g_spawn.i

# target to preprocess a source file
g_spawn.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_spawn.c.i
.PHONY : g_spawn.c.i

g_spawn.s: g_spawn.c.s
.PHONY : g_spawn.s

# target to generate assembly for a file
g_spawn.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_spawn.c.s
.PHONY : g_spawn.c.s

g_svcmds.obj: g_svcmds.c.obj
.PHONY : g_svcmds.obj

# target to build an object file
g_svcmds.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_svcmds.c.obj
.PHONY : g_svcmds.c.obj

g_svcmds.i: g_svcmds.c.i
.PHONY : g_svcmds.i

# target to preprocess a source file
g_svcmds.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_svcmds.c.i
.PHONY : g_svcmds.c.i

g_svcmds.s: g_svcmds.c.s
.PHONY : g_svcmds.s

# target to generate assembly for a file
g_svcmds.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_svcmds.c.s
.PHONY : g_svcmds.c.s

g_sword.obj: g_sword.c.obj
.PHONY : g_sword.obj

# target to build an object file
g_sword.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_sword.c.obj
.PHONY : g_sword.c.obj

g_sword.i: g_sword.c.i
.PHONY : g_sword.i

# target to preprocess a source file
g_sword.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_sword.c.i
.PHONY : g_sword.c.i

g_sword.s: g_sword.c.s
.PHONY : g_sword.s

# target to generate assembly for a file
g_sword.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_sword.c.s
.PHONY : g_sword.c.s

g_target.obj: g_target.c.obj
.PHONY : g_target.obj

# target to build an object file
g_target.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_target.c.obj
.PHONY : g_target.c.obj

g_target.i: g_target.c.i
.PHONY : g_target.i

# target to preprocess a source file
g_target.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_target.c.i
.PHONY : g_target.c.i

g_target.s: g_target.c.s
.PHONY : g_target.s

# target to generate assembly for a file
g_target.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_target.c.s
.PHONY : g_target.c.s

g_trigger.obj: g_trigger.c.obj
.PHONY : g_trigger.obj

# target to build an object file
g_trigger.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_trigger.c.obj
.PHONY : g_trigger.c.obj

g_trigger.i: g_trigger.c.i
.PHONY : g_trigger.i

# target to preprocess a source file
g_trigger.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_trigger.c.i
.PHONY : g_trigger.c.i

g_trigger.s: g_trigger.c.s
.PHONY : g_trigger.s

# target to generate assembly for a file
g_trigger.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_trigger.c.s
.PHONY : g_trigger.c.s

g_utils.obj: g_utils.c.obj
.PHONY : g_utils.obj

# target to build an object file
g_utils.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_utils.c.obj
.PHONY : g_utils.c.obj

g_utils.i: g_utils.c.i
.PHONY : g_utils.i

# target to preprocess a source file
g_utils.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_utils.c.i
.PHONY : g_utils.c.i

g_utils.s: g_utils.c.s
.PHONY : g_utils.s

# target to generate assembly for a file
g_utils.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_utils.c.s
.PHONY : g_utils.c.s

g_weapon.obj: g_weapon.c.obj
.PHONY : g_weapon.obj

# target to build an object file
g_weapon.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_weapon.c.obj
.PHONY : g_weapon.c.obj

g_weapon.i: g_weapon.c.i
.PHONY : g_weapon.i

# target to preprocess a source file
g_weapon.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_weapon.c.i
.PHONY : g_weapon.c.i

g_weapon.s: g_weapon.c.s
.PHONY : g_weapon.s

# target to generate assembly for a file
g_weapon.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/g_weapon.c.s
.PHONY : g_weapon.c.s

grid.obj: grid.c.obj
.PHONY : grid.obj

# target to build an object file
grid.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/grid.c.obj
.PHONY : grid.c.obj

grid.i: grid.c.i
.PHONY : grid.i

# target to preprocess a source file
grid.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/grid.c.i
.PHONY : grid.c.i

grid.s: grid.c.s
.PHONY : grid.s

# target to generate assembly for a file
grid.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/grid.c.s
.PHONY : grid.c.s

hash_32a.obj: hash_32a.c.obj
.PHONY : hash_32a.obj

# target to build an object file
hash_32a.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/hash_32a.c.obj
.PHONY : hash_32a.c.obj

hash_32a.i: hash_32a.c.i
.PHONY : hash_32a.i

# target to preprocess a source file
hash_32a.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/hash_32a.c.i
.PHONY : hash_32a.c.i

hash_32a.s: hash_32a.c.s
.PHONY : hash_32a.s

# target to generate assembly for a file
hash_32a.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/hash_32a.c.s
.PHONY : hash_32a.c.s

help.obj: help.c.obj
.PHONY : help.obj

# target to build an object file
help.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/help.c.obj
.PHONY : help.c.obj

help.i: help.c.i
.PHONY : help.i

# target to preprocess a source file
help.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/help.c.i
.PHONY : help.c.i

help.s: help.c.s
.PHONY : help.s

# target to generate assembly for a file
help.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/help.c.s
.PHONY : help.c.s

invasion.obj: invasion.c.obj
.PHONY : invasion.obj

# target to build an object file
invasion.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/invasion.c.obj
.PHONY : invasion.c.obj

invasion.i: invasion.c.i
.PHONY : invasion.i

# target to preprocess a source file
invasion.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/invasion.c.i
.PHONY : invasion.c.i

invasion.s: invasion.c.s
.PHONY : invasion.s

# target to generate assembly for a file
invasion.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/invasion.c.s
.PHONY : invasion.c.s

item_menu.obj: item_menu.c.obj
.PHONY : item_menu.obj

# target to build an object file
item_menu.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/item_menu.c.obj
.PHONY : item_menu.c.obj

item_menu.i: item_menu.c.i
.PHONY : item_menu.i

# target to preprocess a source file
item_menu.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/item_menu.c.i
.PHONY : item_menu.c.i

item_menu.s: item_menu.c.s
.PHONY : item_menu.s

# target to generate assembly for a file
item_menu.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/item_menu.c.s
.PHONY : item_menu.c.s

jetpack.obj: jetpack.c.obj
.PHONY : jetpack.obj

# target to build an object file
jetpack.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/jetpack.c.obj
.PHONY : jetpack.c.obj

jetpack.i: jetpack.c.i
.PHONY : jetpack.i

# target to preprocess a source file
jetpack.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/jetpack.c.i
.PHONY : jetpack.c.i

jetpack.s: jetpack.c.s
.PHONY : jetpack.s

# target to generate assembly for a file
jetpack.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/jetpack.c.s
.PHONY : jetpack.c.s

lasers.obj: lasers.c.obj
.PHONY : lasers.obj

# target to build an object file
lasers.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lasers.c.obj
.PHONY : lasers.c.obj

lasers.i: lasers.c.i
.PHONY : lasers.i

# target to preprocess a source file
lasers.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lasers.c.i
.PHONY : lasers.c.i

lasers.s: lasers.c.s
.PHONY : lasers.s

# target to generate assembly for a file
lasers.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lasers.c.s
.PHONY : lasers.c.s

lasersight.obj: lasersight.c.obj
.PHONY : lasersight.obj

# target to build an object file
lasersight.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lasersight.c.obj
.PHONY : lasersight.c.obj

lasersight.i: lasersight.c.i
.PHONY : lasersight.i

# target to preprocess a source file
lasersight.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lasersight.c.i
.PHONY : lasersight.c.i

lasersight.s: lasersight.c.s
.PHONY : lasersight.s

# target to generate assembly for a file
lasersight.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lasersight.c.s
.PHONY : lasersight.c.s

laserstuff.obj: laserstuff.c.obj
.PHONY : laserstuff.obj

# target to build an object file
laserstuff.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/laserstuff.c.obj
.PHONY : laserstuff.c.obj

laserstuff.i: laserstuff.c.i
.PHONY : laserstuff.i

# target to preprocess a source file
laserstuff.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/laserstuff.c.i
.PHONY : laserstuff.c.i

laserstuff.s: laserstuff.c.s
.PHONY : laserstuff.s

# target to generate assembly for a file
laserstuff.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/laserstuff.c.s
.PHONY : laserstuff.c.s

lua.obj: lua.c.obj
.PHONY : lua.obj

# target to build an object file
lua.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lua.c.obj
.PHONY : lua.c.obj

lua.i: lua.c.i
.PHONY : lua.i

# target to preprocess a source file
lua.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lua.c.i
.PHONY : lua.c.i

lua.s: lua.c.s
.PHONY : lua.s

# target to generate assembly for a file
lua.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/lua.c.s
.PHONY : lua.c.s

m_flash.obj: m_flash.c.obj
.PHONY : m_flash.obj

# target to build an object file
m_flash.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/m_flash.c.obj
.PHONY : m_flash.c.obj

m_flash.i: m_flash.c.i
.PHONY : m_flash.i

# target to preprocess a source file
m_flash.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/m_flash.c.i
.PHONY : m_flash.c.i

m_flash.s: m_flash.c.s
.PHONY : m_flash.s

# target to generate assembly for a file
m_flash.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/m_flash.c.s
.PHONY : m_flash.c.s

magic.obj: magic.c.obj
.PHONY : magic.obj

# target to build an object file
magic.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/magic.c.obj
.PHONY : magic.c.obj

magic.i: magic.c.i
.PHONY : magic.i

# target to preprocess a source file
magic.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/magic.c.i
.PHONY : magic.c.i

magic.s: magic.c.s
.PHONY : magic.s

# target to generate assembly for a file
magic.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/magic.c.s
.PHONY : magic.c.s

maplist.obj: maplist.c.obj
.PHONY : maplist.obj

# target to build an object file
maplist.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/maplist.c.obj
.PHONY : maplist.c.obj

maplist.i: maplist.c.i
.PHONY : maplist.i

# target to preprocess a source file
maplist.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/maplist.c.i
.PHONY : maplist.c.i

maplist.s: maplist.c.s
.PHONY : maplist.s

# target to generate assembly for a file
maplist.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/maplist.c.s
.PHONY : maplist.c.s

menu.obj: menu.c.obj
.PHONY : menu.obj

# target to build an object file
menu.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/menu.c.obj
.PHONY : menu.c.obj

menu.i: menu.c.i
.PHONY : menu.i

# target to preprocess a source file
menu.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/menu.c.i
.PHONY : menu.c.i

menu.s: menu.c.s
.PHONY : menu.s

# target to generate assembly for a file
menu.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/menu.c.s
.PHONY : menu.c.s

minisentry.obj: minisentry.c.obj
.PHONY : minisentry.obj

# target to build an object file
minisentry.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/minisentry.c.obj
.PHONY : minisentry.c.obj

minisentry.i: minisentry.c.i
.PHONY : minisentry.i

# target to preprocess a source file
minisentry.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/minisentry.c.i
.PHONY : minisentry.c.i

minisentry.s: minisentry.c.s
.PHONY : minisentry.s

# target to generate assembly for a file
minisentry.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/minisentry.c.s
.PHONY : minisentry.c.s

misc_stuff.obj: misc_stuff.c.obj
.PHONY : misc_stuff.obj

# target to build an object file
misc_stuff.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/misc_stuff.c.obj
.PHONY : misc_stuff.c.obj

misc_stuff.i: misc_stuff.c.i
.PHONY : misc_stuff.i

# target to preprocess a source file
misc_stuff.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/misc_stuff.c.i
.PHONY : misc_stuff.c.i

misc_stuff.s: misc_stuff.c.s
.PHONY : misc_stuff.s

# target to generate assembly for a file
misc_stuff.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/misc_stuff.c.s
.PHONY : misc_stuff.c.s

p_client.obj: p_client.c.obj
.PHONY : p_client.obj

# target to build an object file
p_client.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_client.c.obj
.PHONY : p_client.c.obj

p_client.i: p_client.c.i
.PHONY : p_client.i

# target to preprocess a source file
p_client.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_client.c.i
.PHONY : p_client.c.i

p_client.s: p_client.c.s
.PHONY : p_client.s

# target to generate assembly for a file
p_client.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_client.c.s
.PHONY : p_client.c.s

p_hook.obj: p_hook.c.obj
.PHONY : p_hook.obj

# target to build an object file
p_hook.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_hook.c.obj
.PHONY : p_hook.c.obj

p_hook.i: p_hook.c.i
.PHONY : p_hook.i

# target to preprocess a source file
p_hook.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_hook.c.i
.PHONY : p_hook.c.i

p_hook.s: p_hook.c.s
.PHONY : p_hook.s

# target to generate assembly for a file
p_hook.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_hook.c.s
.PHONY : p_hook.c.s

p_hud.obj: p_hud.c.obj
.PHONY : p_hud.obj

# target to build an object file
p_hud.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_hud.c.obj
.PHONY : p_hud.c.obj

p_hud.i: p_hud.c.i
.PHONY : p_hud.i

# target to preprocess a source file
p_hud.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_hud.c.i
.PHONY : p_hud.c.i

p_hud.s: p_hud.c.s
.PHONY : p_hud.s

# target to generate assembly for a file
p_hud.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_hud.c.s
.PHONY : p_hud.c.s

p_menu.obj: p_menu.c.obj
.PHONY : p_menu.obj

# target to build an object file
p_menu.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_menu.c.obj
.PHONY : p_menu.c.obj

p_menu.i: p_menu.c.i
.PHONY : p_menu.i

# target to preprocess a source file
p_menu.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_menu.c.i
.PHONY : p_menu.c.i

p_menu.s: p_menu.c.s
.PHONY : p_menu.s

# target to generate assembly for a file
p_menu.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_menu.c.s
.PHONY : p_menu.c.s

p_parasite.obj: p_parasite.c.obj
.PHONY : p_parasite.obj

# target to build an object file
p_parasite.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_parasite.c.obj
.PHONY : p_parasite.c.obj

p_parasite.i: p_parasite.c.i
.PHONY : p_parasite.i

# target to preprocess a source file
p_parasite.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_parasite.c.i
.PHONY : p_parasite.c.i

p_parasite.s: p_parasite.c.s
.PHONY : p_parasite.s

# target to generate assembly for a file
p_parasite.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_parasite.c.s
.PHONY : p_parasite.c.s

p_trail.obj: p_trail.c.obj
.PHONY : p_trail.obj

# target to build an object file
p_trail.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_trail.c.obj
.PHONY : p_trail.c.obj

p_trail.i: p_trail.c.i
.PHONY : p_trail.i

# target to preprocess a source file
p_trail.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_trail.c.i
.PHONY : p_trail.c.i

p_trail.s: p_trail.c.s
.PHONY : p_trail.s

# target to generate assembly for a file
p_trail.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_trail.c.s
.PHONY : p_trail.c.s

p_view.obj: p_view.c.obj
.PHONY : p_view.obj

# target to build an object file
p_view.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_view.c.obj
.PHONY : p_view.c.obj

p_view.i: p_view.c.i
.PHONY : p_view.i

# target to preprocess a source file
p_view.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_view.c.i
.PHONY : p_view.c.i

p_view.s: p_view.c.s
.PHONY : p_view.s

# target to generate assembly for a file
p_view.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_view.c.s
.PHONY : p_view.c.s

p_weapon.obj: p_weapon.c.obj
.PHONY : p_weapon.obj

# target to build an object file
p_weapon.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_weapon.c.obj
.PHONY : p_weapon.c.obj

p_weapon.i: p_weapon.c.i
.PHONY : p_weapon.i

# target to preprocess a source file
p_weapon.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_weapon.c.i
.PHONY : p_weapon.c.i

p_weapon.s: p_weapon.c.s
.PHONY : p_weapon.s

# target to generate assembly for a file
p_weapon.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/p_weapon.c.s
.PHONY : p_weapon.c.s

player_points.obj: player_points.c.obj
.PHONY : player_points.obj

# target to build an object file
player_points.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/player_points.c.obj
.PHONY : player_points.c.obj

player_points.i: player_points.c.i
.PHONY : player_points.i

# target to preprocess a source file
player_points.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/player_points.c.i
.PHONY : player_points.c.i

player_points.s: player_points.c.s
.PHONY : player_points.s

# target to generate assembly for a file
player_points.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/player_points.c.s
.PHONY : player_points.c.s

playerlog.obj: playerlog.c.obj
.PHONY : playerlog.obj

# target to build an object file
playerlog.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playerlog.c.obj
.PHONY : playerlog.c.obj

playerlog.i: playerlog.c.i
.PHONY : playerlog.i

# target to preprocess a source file
playerlog.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playerlog.c.i
.PHONY : playerlog.c.i

playerlog.s: playerlog.c.s
.PHONY : playerlog.s

# target to generate assembly for a file
playerlog.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playerlog.c.s
.PHONY : playerlog.c.s

playertoberserk.obj: playertoberserk.c.obj
.PHONY : playertoberserk.obj

# target to build an object file
playertoberserk.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoberserk.c.obj
.PHONY : playertoberserk.c.obj

playertoberserk.i: playertoberserk.c.i
.PHONY : playertoberserk.i

# target to preprocess a source file
playertoberserk.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoberserk.c.i
.PHONY : playertoberserk.c.i

playertoberserk.s: playertoberserk.c.s
.PHONY : playertoberserk.s

# target to generate assembly for a file
playertoberserk.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoberserk.c.s
.PHONY : playertoberserk.c.s

playertoflyer.obj: playertoflyer.c.obj
.PHONY : playertoflyer.obj

# target to build an object file
playertoflyer.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoflyer.c.obj
.PHONY : playertoflyer.c.obj

playertoflyer.i: playertoflyer.c.i
.PHONY : playertoflyer.i

# target to preprocess a source file
playertoflyer.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoflyer.c.i
.PHONY : playertoflyer.c.i

playertoflyer.s: playertoflyer.c.s
.PHONY : playertoflyer.s

# target to generate assembly for a file
playertoflyer.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoflyer.c.s
.PHONY : playertoflyer.c.s

playertomedic.obj: playertomedic.c.obj
.PHONY : playertomedic.obj

# target to build an object file
playertomedic.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertomedic.c.obj
.PHONY : playertomedic.c.obj

playertomedic.i: playertomedic.c.i
.PHONY : playertomedic.i

# target to preprocess a source file
playertomedic.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertomedic.c.i
.PHONY : playertomedic.c.i

playertomedic.s: playertomedic.c.s
.PHONY : playertomedic.s

# target to generate assembly for a file
playertomedic.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertomedic.c.s
.PHONY : playertomedic.c.s

playertomutant.obj: playertomutant.c.obj
.PHONY : playertomutant.obj

# target to build an object file
playertomutant.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertomutant.c.obj
.PHONY : playertomutant.c.obj

playertomutant.i: playertomutant.c.i
.PHONY : playertomutant.i

# target to preprocess a source file
playertomutant.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertomutant.c.i
.PHONY : playertomutant.c.i

playertomutant.s: playertomutant.c.s
.PHONY : playertomutant.s

# target to generate assembly for a file
playertomutant.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertomutant.c.s
.PHONY : playertomutant.c.s

playertoparasite.obj: playertoparasite.c.obj
.PHONY : playertoparasite.obj

# target to build an object file
playertoparasite.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoparasite.c.obj
.PHONY : playertoparasite.c.obj

playertoparasite.i: playertoparasite.c.i
.PHONY : playertoparasite.i

# target to preprocess a source file
playertoparasite.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoparasite.c.i
.PHONY : playertoparasite.c.i

playertoparasite.s: playertoparasite.c.s
.PHONY : playertoparasite.s

# target to generate assembly for a file
playertoparasite.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertoparasite.c.s
.PHONY : playertoparasite.c.s

playertotank.obj: playertotank.c.obj
.PHONY : playertotank.obj

# target to build an object file
playertotank.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertotank.c.obj
.PHONY : playertotank.c.obj

playertotank.i: playertotank.c.i
.PHONY : playertotank.i

# target to preprocess a source file
playertotank.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertotank.c.i
.PHONY : playertotank.c.i

playertotank.s: playertotank.c.s
.PHONY : playertotank.s

# target to generate assembly for a file
playertotank.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/playertotank.c.s
.PHONY : playertotank.c.s

pvb.obj: pvb.c.obj
.PHONY : pvb.obj

# target to build an object file
pvb.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/pvb.c.obj
.PHONY : pvb.c.obj

pvb.i: pvb.c.i
.PHONY : pvb.i

# target to preprocess a source file
pvb.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/pvb.c.i
.PHONY : pvb.c.i

pvb.s: pvb.c.s
.PHONY : pvb.s

# target to generate assembly for a file
pvb.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/pvb.c.s
.PHONY : pvb.c.s

q_shared.obj: q_shared.c.obj
.PHONY : q_shared.obj

# target to build an object file
q_shared.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/q_shared.c.obj
.PHONY : q_shared.c.obj

q_shared.i: q_shared.c.i
.PHONY : q_shared.i

# target to preprocess a source file
q_shared.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/q_shared.c.i
.PHONY : q_shared.c.i

q_shared.s: q_shared.c.s
.PHONY : q_shared.s

# target to generate assembly for a file
q_shared.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/q_shared.c.s
.PHONY : q_shared.c.s

repairstation.obj: repairstation.c.obj
.PHONY : repairstation.obj

# target to build an object file
repairstation.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/repairstation.c.obj
.PHONY : repairstation.c.obj

repairstation.i: repairstation.c.i
.PHONY : repairstation.i

# target to preprocess a source file
repairstation.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/repairstation.c.i
.PHONY : repairstation.c.i

repairstation.s: repairstation.c.s
.PHONY : repairstation.s

# target to generate assembly for a file
repairstation.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/repairstation.c.s
.PHONY : repairstation.c.s

scanner.obj: scanner.c.obj
.PHONY : scanner.obj

# target to build an object file
scanner.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/scanner.c.obj
.PHONY : scanner.c.obj

scanner.i: scanner.c.i
.PHONY : scanner.i

# target to preprocess a source file
scanner.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/scanner.c.i
.PHONY : scanner.c.i

scanner.s: scanner.c.s
.PHONY : scanner.s

# target to generate assembly for a file
scanner.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/scanner.c.s
.PHONY : scanner.c.s

sentrygun2.obj: sentrygun2.c.obj
.PHONY : sentrygun2.obj

# target to build an object file
sentrygun2.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/sentrygun2.c.obj
.PHONY : sentrygun2.c.obj

sentrygun2.i: sentrygun2.c.i
.PHONY : sentrygun2.i

# target to preprocess a source file
sentrygun2.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/sentrygun2.c.i
.PHONY : sentrygun2.c.i

sentrygun2.s: sentrygun2.c.s
.PHONY : sentrygun2.s

# target to generate assembly for a file
sentrygun2.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/sentrygun2.c.s
.PHONY : sentrygun2.c.s

shaman.obj: shaman.c.obj
.PHONY : shaman.obj

# target to build an object file
shaman.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/shaman.c.obj
.PHONY : shaman.c.obj

shaman.i: shaman.c.i
.PHONY : shaman.i

# target to preprocess a source file
shaman.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/shaman.c.i
.PHONY : shaman.c.i

shaman.s: shaman.c.s
.PHONY : shaman.s

# target to generate assembly for a file
shaman.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/shaman.c.s
.PHONY : shaman.c.s

special_items.obj: special_items.c.obj
.PHONY : special_items.obj

# target to build an object file
special_items.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/special_items.c.obj
.PHONY : special_items.c.obj

special_items.i: special_items.c.i
.PHONY : special_items.i

# target to preprocess a source file
special_items.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/special_items.c.i
.PHONY : special_items.c.i

special_items.s: special_items.c.s
.PHONY : special_items.s

# target to generate assembly for a file
special_items.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/special_items.c.s
.PHONY : special_items.c.s

sqlite3.obj: sqlite3.c.obj
.PHONY : sqlite3.obj

# target to build an object file
sqlite3.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/sqlite3.c.obj
.PHONY : sqlite3.c.obj

sqlite3.i: sqlite3.c.i
.PHONY : sqlite3.i

# target to preprocess a source file
sqlite3.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/sqlite3.c.i
.PHONY : sqlite3.c.i

sqlite3.s: sqlite3.c.s
.PHONY : sqlite3.s

# target to generate assembly for a file
sqlite3.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/sqlite3.c.s
.PHONY : sqlite3.c.s

supplystation.obj: supplystation.c.obj
.PHONY : supplystation.obj

# target to build an object file
supplystation.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/supplystation.c.obj
.PHONY : supplystation.c.obj

supplystation.i: supplystation.c.i
.PHONY : supplystation.i

# target to preprocess a source file
supplystation.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/supplystation.c.i
.PHONY : supplystation.c.i

supplystation.s: supplystation.c.s
.PHONY : supplystation.s

# target to generate assembly for a file
supplystation.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/supplystation.c.s
.PHONY : supplystation.c.s

teamplay.obj: teamplay.c.obj
.PHONY : teamplay.obj

# target to build an object file
teamplay.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/teamplay.c.obj
.PHONY : teamplay.c.obj

teamplay.i: teamplay.c.i
.PHONY : teamplay.i

# target to preprocess a source file
teamplay.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/teamplay.c.i
.PHONY : teamplay.c.i

teamplay.s: teamplay.c.s
.PHONY : teamplay.s

# target to generate assembly for a file
teamplay.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/teamplay.c.s
.PHONY : teamplay.c.s

totems.obj: totems.c.obj
.PHONY : totems.obj

# target to build an object file
totems.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/totems.c.obj
.PHONY : totems.c.obj

totems.i: totems.c.i
.PHONY : totems.i

# target to preprocess a source file
totems.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/totems.c.i
.PHONY : totems.c.i

totems.s: totems.c.s
.PHONY : totems.s

# target to generate assembly for a file
totems.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/totems.c.s
.PHONY : totems.c.s

trade.obj: trade.c.obj
.PHONY : trade.obj

# target to build an object file
trade.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/trade.c.obj
.PHONY : trade.c.obj

trade.i: trade.c.i
.PHONY : trade.i

# target to preprocess a source file
trade.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/trade.c.i
.PHONY : trade.c.i

trade.s: trade.c.s
.PHONY : trade.s

# target to generate assembly for a file
trade.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/trade.c.s
.PHONY : trade.c.s

upgrades.obj: upgrades.c.obj
.PHONY : upgrades.obj

# target to build an object file
upgrades.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/upgrades.c.obj
.PHONY : upgrades.c.obj

upgrades.i: upgrades.c.i
.PHONY : upgrades.i

# target to preprocess a source file
upgrades.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/upgrades.c.i
.PHONY : upgrades.c.i

upgrades.s: upgrades.c.s
.PHONY : upgrades.s

# target to generate assembly for a file
upgrades.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/upgrades.c.s
.PHONY : upgrades.c.s

v_abilitylist.obj: v_abilitylist.c.obj
.PHONY : v_abilitylist.obj

# target to build an object file
v_abilitylist.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_abilitylist.c.obj
.PHONY : v_abilitylist.c.obj

v_abilitylist.i: v_abilitylist.c.i
.PHONY : v_abilitylist.i

# target to preprocess a source file
v_abilitylist.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_abilitylist.c.i
.PHONY : v_abilitylist.c.i

v_abilitylist.s: v_abilitylist.c.s
.PHONY : v_abilitylist.s

# target to generate assembly for a file
v_abilitylist.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_abilitylist.c.s
.PHONY : v_abilitylist.c.s

v_autobind.obj: v_autobind.c.obj
.PHONY : v_autobind.obj

# target to build an object file
v_autobind.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_autobind.c.obj
.PHONY : v_autobind.c.obj

v_autobind.i: v_autobind.c.i
.PHONY : v_autobind.i

# target to preprocess a source file
v_autobind.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_autobind.c.i
.PHONY : v_autobind.c.i

v_autobind.s: v_autobind.c.s
.PHONY : v_autobind.s

# target to generate assembly for a file
v_autobind.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_autobind.c.s
.PHONY : v_autobind.c.s

v_cmd.obj: v_cmd.c.obj
.PHONY : v_cmd.obj

# target to build an object file
v_cmd.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_cmd.c.obj
.PHONY : v_cmd.c.obj

v_cmd.i: v_cmd.c.i
.PHONY : v_cmd.i

# target to preprocess a source file
v_cmd.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_cmd.c.i
.PHONY : v_cmd.c.i

v_cmd.s: v_cmd.c.s
.PHONY : v_cmd.s

# target to generate assembly for a file
v_cmd.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_cmd.c.s
.PHONY : v_cmd.c.s

v_file_IO.obj: v_file_IO.c.obj
.PHONY : v_file_IO.obj

# target to build an object file
v_file_IO.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_file_IO.c.obj
.PHONY : v_file_IO.c.obj

v_file_IO.i: v_file_IO.c.i
.PHONY : v_file_IO.i

# target to preprocess a source file
v_file_IO.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_file_IO.c.i
.PHONY : v_file_IO.c.i

v_file_IO.s: v_file_IO.c.s
.PHONY : v_file_IO.s

# target to generate assembly for a file
v_file_IO.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_file_IO.c.s
.PHONY : v_file_IO.c.s

v_hw.obj: v_hw.c.obj
.PHONY : v_hw.obj

# target to build an object file
v_hw.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_hw.c.obj
.PHONY : v_hw.c.obj

v_hw.i: v_hw.c.i
.PHONY : v_hw.i

# target to preprocess a source file
v_hw.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_hw.c.i
.PHONY : v_hw.c.i

v_hw.s: v_hw.c.s
.PHONY : v_hw.s

# target to generate assembly for a file
v_hw.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_hw.c.s
.PHONY : v_hw.c.s

v_items.obj: v_items.c.obj
.PHONY : v_items.obj

# target to build an object file
v_items.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_items.c.obj
.PHONY : v_items.c.obj

v_items.i: v_items.c.i
.PHONY : v_items.i

# target to preprocess a source file
v_items.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_items.c.i
.PHONY : v_items.c.i

v_items.s: v_items.c.s
.PHONY : v_items.s

# target to generate assembly for a file
v_items.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_items.c.s
.PHONY : v_items.c.s

v_luasettings.obj: v_luasettings.c.obj
.PHONY : v_luasettings.obj

# target to build an object file
v_luasettings.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_luasettings.c.obj
.PHONY : v_luasettings.c.obj

v_luasettings.i: v_luasettings.c.i
.PHONY : v_luasettings.i

# target to preprocess a source file
v_luasettings.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_luasettings.c.i
.PHONY : v_luasettings.c.i

v_luasettings.s: v_luasettings.c.s
.PHONY : v_luasettings.s

# target to generate assembly for a file
v_luasettings.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_luasettings.c.s
.PHONY : v_luasettings.c.s

v_maplist.obj: v_maplist.c.obj
.PHONY : v_maplist.obj

# target to build an object file
v_maplist.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_maplist.c.obj
.PHONY : v_maplist.c.obj

v_maplist.i: v_maplist.c.i
.PHONY : v_maplist.i

# target to preprocess a source file
v_maplist.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_maplist.c.i
.PHONY : v_maplist.c.i

v_maplist.s: v_maplist.c.s
.PHONY : v_maplist.s

# target to generate assembly for a file
v_maplist.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_maplist.c.s
.PHONY : v_maplist.c.s

v_mysql_gds.obj: v_mysql_gds.c.obj
.PHONY : v_mysql_gds.obj

# target to build an object file
v_mysql_gds.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_mysql_gds.c.obj
.PHONY : v_mysql_gds.c.obj

v_mysql_gds.i: v_mysql_gds.c.i
.PHONY : v_mysql_gds.i

# target to preprocess a source file
v_mysql_gds.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_mysql_gds.c.i
.PHONY : v_mysql_gds.c.i

v_mysql_gds.s: v_mysql_gds.c.s
.PHONY : v_mysql_gds.s

# target to generate assembly for a file
v_mysql_gds.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_mysql_gds.c.s
.PHONY : v_mysql_gds.c.s

v_sqlite_character.obj: v_sqlite_character.c.obj
.PHONY : v_sqlite_character.obj

# target to build an object file
v_sqlite_character.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_sqlite_character.c.obj
.PHONY : v_sqlite_character.c.obj

v_sqlite_character.i: v_sqlite_character.c.i
.PHONY : v_sqlite_character.i

# target to preprocess a source file
v_sqlite_character.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_sqlite_character.c.i
.PHONY : v_sqlite_character.c.i

v_sqlite_character.s: v_sqlite_character.c.s
.PHONY : v_sqlite_character.s

# target to generate assembly for a file
v_sqlite_character.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_sqlite_character.c.s
.PHONY : v_sqlite_character.c.s

v_sqlite_unidb.obj: v_sqlite_unidb.c.obj
.PHONY : v_sqlite_unidb.obj

# target to build an object file
v_sqlite_unidb.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_sqlite_unidb.c.obj
.PHONY : v_sqlite_unidb.c.obj

v_sqlite_unidb.i: v_sqlite_unidb.c.i
.PHONY : v_sqlite_unidb.i

# target to preprocess a source file
v_sqlite_unidb.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_sqlite_unidb.c.i
.PHONY : v_sqlite_unidb.c.i

v_sqlite_unidb.s: v_sqlite_unidb.c.s
.PHONY : v_sqlite_unidb.s

# target to generate assembly for a file
v_sqlite_unidb.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_sqlite_unidb.c.s
.PHONY : v_sqlite_unidb.c.s

v_tbi.obj: v_tbi.c.obj
.PHONY : v_tbi.obj

# target to build an object file
v_tbi.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_tbi.c.obj
.PHONY : v_tbi.c.obj

v_tbi.i: v_tbi.c.i
.PHONY : v_tbi.i

# target to preprocess a source file
v_tbi.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_tbi.c.i
.PHONY : v_tbi.c.i

v_tbi.s: v_tbi.c.s
.PHONY : v_tbi.s

# target to generate assembly for a file
v_tbi.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_tbi.c.s
.PHONY : v_tbi.c.s

v_utils.obj: v_utils.c.obj
.PHONY : v_utils.obj

# target to build an object file
v_utils.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_utils.c.obj
.PHONY : v_utils.c.obj

v_utils.i: v_utils.c.i
.PHONY : v_utils.i

# target to preprocess a source file
v_utils.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_utils.c.i
.PHONY : v_utils.c.i

v_utils.s: v_utils.c.s
.PHONY : v_utils.s

# target to generate assembly for a file
v_utils.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/v_utils.c.s
.PHONY : v_utils.c.s

vote.obj: vote.c.obj
.PHONY : vote.obj

# target to build an object file
vote.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/vote.c.obj
.PHONY : vote.c.obj

vote.i: vote.c.i
.PHONY : vote.i

# target to preprocess a source file
vote.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/vote.c.i
.PHONY : vote.c.i

vote.s: vote.c.s
.PHONY : vote.s

# target to generate assembly for a file
vote.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/vote.c.s
.PHONY : vote.c.s

weapon_upgrades.obj: weapon_upgrades.c.obj
.PHONY : weapon_upgrades.obj

# target to build an object file
weapon_upgrades.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/weapon_upgrades.c.obj
.PHONY : weapon_upgrades.c.obj

weapon_upgrades.i: weapon_upgrades.c.i
.PHONY : weapon_upgrades.i

# target to preprocess a source file
weapon_upgrades.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/weapon_upgrades.c.i
.PHONY : weapon_upgrades.c.i

weapon_upgrades.s: weapon_upgrades.c.s
.PHONY : weapon_upgrades.s

# target to generate assembly for a file
weapon_upgrades.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/weapon_upgrades.c.s
.PHONY : weapon_upgrades.c.s

weapons.obj: weapons.c.obj
.PHONY : weapons.obj

# target to build an object file
weapons.c.obj:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/weapons.c.obj
.PHONY : weapons.c.obj

weapons.i: weapons.c.i
.PHONY : weapons.i

# target to preprocess a source file
weapons.c.i:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/weapons.c.i
.PHONY : weapons.c.i

weapons.s: weapons.c.s
.PHONY : weapons.s

# target to generate assembly for a file
weapons.c.s:
	$(MAKE) -f CMakeFiles\gamex86.dir\build.make CMakeFiles/gamex86.dir/weapons.c.s
.PHONY : weapons.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... gamex86
	@echo ... Player.obj
	@echo ... Player.i
	@echo ... Player.s
	@echo ... Spirit.obj
	@echo ... Spirit.i
	@echo ... Spirit.s
	@echo ... Talents.obj
	@echo ... Talents.i
	@echo ... Talents.s
	@echo ... ai/AStar.obj
	@echo ... ai/AStar.i
	@echo ... ai/AStar.s
	@echo ... ai/ai_class_dmbot.obj
	@echo ... ai/ai_class_dmbot.i
	@echo ... ai/ai_class_dmbot.s
	@echo ... ai/ai_class_monster_default.obj
	@echo ... ai/ai_class_monster_default.i
	@echo ... ai/ai_class_monster_default.s
	@echo ... ai/ai_dropnodes.obj
	@echo ... ai/ai_dropnodes.i
	@echo ... ai/ai_dropnodes.s
	@echo ... ai/ai_items.obj
	@echo ... ai/ai_items.i
	@echo ... ai/ai_items.s
	@echo ... ai/ai_links.obj
	@echo ... ai/ai_links.i
	@echo ... ai/ai_links.s
	@echo ... ai/ai_main.obj
	@echo ... ai/ai_main.i
	@echo ... ai/ai_main.s
	@echo ... ai/ai_movement.obj
	@echo ... ai/ai_movement.i
	@echo ... ai/ai_movement.s
	@echo ... ai/ai_navigation.obj
	@echo ... ai/ai_navigation.i
	@echo ... ai/ai_navigation.s
	@echo ... ai/ai_nodes.obj
	@echo ... ai/ai_nodes.i
	@echo ... ai/ai_nodes.s
	@echo ... ai/ai_tools.obj
	@echo ... ai/ai_tools.i
	@echo ... ai/ai_tools.s
	@echo ... ai/ai_weapons.obj
	@echo ... ai/ai_weapons.i
	@echo ... ai/ai_weapons.s
	@echo ... ai/bot_common.obj
	@echo ... ai/bot_common.i
	@echo ... ai/bot_common.s
	@echo ... ai/bot_spawn.obj
	@echo ... ai/bot_spawn.i
	@echo ... ai/bot_spawn.s
	@echo ... ally.obj
	@echo ... ally.i
	@echo ... ally.s
	@echo ... armory.obj
	@echo ... armory.i
	@echo ... armory.s
	@echo ... auras.obj
	@echo ... auras.i
	@echo ... auras.s
	@echo ... backpack.obj
	@echo ... backpack.i
	@echo ... backpack.s
	@echo ... bombspell.obj
	@echo ... bombspell.i
	@echo ... bombspell.s
	@echo ... boss_general.obj
	@echo ... boss_general.i
	@echo ... boss_general.s
	@echo ... boss_makron.obj
	@echo ... boss_makron.i
	@echo ... boss_makron.s
	@echo ... boss_tank.obj
	@echo ... boss_tank.i
	@echo ... boss_tank.s
	@echo ... class_brain.obj
	@echo ... class_brain.i
	@echo ... class_brain.s
	@echo ... class_demon.obj
	@echo ... class_demon.i
	@echo ... class_demon.s
	@echo ... cloak.obj
	@echo ... cloak.i
	@echo ... cloak.s
	@echo ... ctf.obj
	@echo ... ctf.i
	@echo ... ctf.s
	@echo ... damage.obj
	@echo ... damage.i
	@echo ... damage.s
	@echo ... domination.obj
	@echo ... domination.i
	@echo ... domination.s
	@echo ... drone_ai.obj
	@echo ... drone_ai.i
	@echo ... drone_ai.s
	@echo ... drone_berserk.obj
	@echo ... drone_berserk.i
	@echo ... drone_berserk.s
	@echo ... drone_bitch.obj
	@echo ... drone_bitch.i
	@echo ... drone_bitch.s
	@echo ... drone_brain.obj
	@echo ... drone_brain.i
	@echo ... drone_brain.s
	@echo ... drone_decoy.obj
	@echo ... drone_decoy.i
	@echo ... drone_decoy.s
	@echo ... drone_gladiator.obj
	@echo ... drone_gladiator.i
	@echo ... drone_gladiator.s
	@echo ... drone_gunner.obj
	@echo ... drone_gunner.i
	@echo ... drone_gunner.s
	@echo ... drone_infantry.obj
	@echo ... drone_infantry.i
	@echo ... drone_infantry.s
	@echo ... drone_jorg.obj
	@echo ... drone_jorg.i
	@echo ... drone_jorg.s
	@echo ... drone_makron.obj
	@echo ... drone_makron.i
	@echo ... drone_makron.s
	@echo ... drone_medic.obj
	@echo ... drone_medic.i
	@echo ... drone_medic.s
	@echo ... drone_misc.obj
	@echo ... drone_misc.i
	@echo ... drone_misc.s
	@echo ... drone_move.obj
	@echo ... drone_move.i
	@echo ... drone_move.s
	@echo ... drone_mutant.obj
	@echo ... drone_mutant.i
	@echo ... drone_mutant.s
	@echo ... drone_parasite.obj
	@echo ... drone_parasite.i
	@echo ... drone_parasite.s
	@echo ... drone_retard.obj
	@echo ... drone_retard.i
	@echo ... drone_retard.s
	@echo ... drone_soldier.obj
	@echo ... drone_soldier.i
	@echo ... drone_soldier.s
	@echo ... drone_supertank.obj
	@echo ... drone_supertank.i
	@echo ... drone_supertank.s
	@echo ... drone_tank.obj
	@echo ... drone_tank.i
	@echo ... drone_tank.s
	@echo ... ents.obj
	@echo ... ents.i
	@echo ... ents.s
	@echo ... file_output.obj
	@echo ... file_output.i
	@echo ... file_output.s
	@echo ... flying_skull.obj
	@echo ... flying_skull.i
	@echo ... flying_skull.s
	@echo ... forcewall.obj
	@echo ... forcewall.i
	@echo ... forcewall.s
	@echo ... g_chase.obj
	@echo ... g_chase.i
	@echo ... g_chase.s
	@echo ... g_cmds.obj
	@echo ... g_cmds.i
	@echo ... g_cmds.s
	@echo ... g_combat.obj
	@echo ... g_combat.i
	@echo ... g_combat.s
	@echo ... g_flame.obj
	@echo ... g_flame.i
	@echo ... g_flame.s
	@echo ... g_func.obj
	@echo ... g_func.i
	@echo ... g_func.s
	@echo ... g_items.obj
	@echo ... g_items.i
	@echo ... g_items.s
	@echo ... g_lasers.obj
	@echo ... g_lasers.i
	@echo ... g_lasers.s
	@echo ... g_main.obj
	@echo ... g_main.i
	@echo ... g_main.s
	@echo ... g_misc.obj
	@echo ... g_misc.i
	@echo ... g_misc.s
	@echo ... g_monster.obj
	@echo ... g_monster.i
	@echo ... g_monster.s
	@echo ... g_phys.obj
	@echo ... g_phys.i
	@echo ... g_phys.s
	@echo ... g_save.obj
	@echo ... g_save.i
	@echo ... g_save.s
	@echo ... g_spawn.obj
	@echo ... g_spawn.i
	@echo ... g_spawn.s
	@echo ... g_svcmds.obj
	@echo ... g_svcmds.i
	@echo ... g_svcmds.s
	@echo ... g_sword.obj
	@echo ... g_sword.i
	@echo ... g_sword.s
	@echo ... g_target.obj
	@echo ... g_target.i
	@echo ... g_target.s
	@echo ... g_trigger.obj
	@echo ... g_trigger.i
	@echo ... g_trigger.s
	@echo ... g_utils.obj
	@echo ... g_utils.i
	@echo ... g_utils.s
	@echo ... g_weapon.obj
	@echo ... g_weapon.i
	@echo ... g_weapon.s
	@echo ... grid.obj
	@echo ... grid.i
	@echo ... grid.s
	@echo ... hash_32a.obj
	@echo ... hash_32a.i
	@echo ... hash_32a.s
	@echo ... help.obj
	@echo ... help.i
	@echo ... help.s
	@echo ... invasion.obj
	@echo ... invasion.i
	@echo ... invasion.s
	@echo ... item_menu.obj
	@echo ... item_menu.i
	@echo ... item_menu.s
	@echo ... jetpack.obj
	@echo ... jetpack.i
	@echo ... jetpack.s
	@echo ... lasers.obj
	@echo ... lasers.i
	@echo ... lasers.s
	@echo ... lasersight.obj
	@echo ... lasersight.i
	@echo ... lasersight.s
	@echo ... laserstuff.obj
	@echo ... laserstuff.i
	@echo ... laserstuff.s
	@echo ... lua.obj
	@echo ... lua.i
	@echo ... lua.s
	@echo ... m_flash.obj
	@echo ... m_flash.i
	@echo ... m_flash.s
	@echo ... magic.obj
	@echo ... magic.i
	@echo ... magic.s
	@echo ... maplist.obj
	@echo ... maplist.i
	@echo ... maplist.s
	@echo ... menu.obj
	@echo ... menu.i
	@echo ... menu.s
	@echo ... minisentry.obj
	@echo ... minisentry.i
	@echo ... minisentry.s
	@echo ... misc_stuff.obj
	@echo ... misc_stuff.i
	@echo ... misc_stuff.s
	@echo ... p_client.obj
	@echo ... p_client.i
	@echo ... p_client.s
	@echo ... p_hook.obj
	@echo ... p_hook.i
	@echo ... p_hook.s
	@echo ... p_hud.obj
	@echo ... p_hud.i
	@echo ... p_hud.s
	@echo ... p_menu.obj
	@echo ... p_menu.i
	@echo ... p_menu.s
	@echo ... p_parasite.obj
	@echo ... p_parasite.i
	@echo ... p_parasite.s
	@echo ... p_trail.obj
	@echo ... p_trail.i
	@echo ... p_trail.s
	@echo ... p_view.obj
	@echo ... p_view.i
	@echo ... p_view.s
	@echo ... p_weapon.obj
	@echo ... p_weapon.i
	@echo ... p_weapon.s
	@echo ... player_points.obj
	@echo ... player_points.i
	@echo ... player_points.s
	@echo ... playerlog.obj
	@echo ... playerlog.i
	@echo ... playerlog.s
	@echo ... playertoberserk.obj
	@echo ... playertoberserk.i
	@echo ... playertoberserk.s
	@echo ... playertoflyer.obj
	@echo ... playertoflyer.i
	@echo ... playertoflyer.s
	@echo ... playertomedic.obj
	@echo ... playertomedic.i
	@echo ... playertomedic.s
	@echo ... playertomutant.obj
	@echo ... playertomutant.i
	@echo ... playertomutant.s
	@echo ... playertoparasite.obj
	@echo ... playertoparasite.i
	@echo ... playertoparasite.s
	@echo ... playertotank.obj
	@echo ... playertotank.i
	@echo ... playertotank.s
	@echo ... pvb.obj
	@echo ... pvb.i
	@echo ... pvb.s
	@echo ... q_shared.obj
	@echo ... q_shared.i
	@echo ... q_shared.s
	@echo ... repairstation.obj
	@echo ... repairstation.i
	@echo ... repairstation.s
	@echo ... scanner.obj
	@echo ... scanner.i
	@echo ... scanner.s
	@echo ... sentrygun2.obj
	@echo ... sentrygun2.i
	@echo ... sentrygun2.s
	@echo ... shaman.obj
	@echo ... shaman.i
	@echo ... shaman.s
	@echo ... special_items.obj
	@echo ... special_items.i
	@echo ... special_items.s
	@echo ... sqlite3.obj
	@echo ... sqlite3.i
	@echo ... sqlite3.s
	@echo ... supplystation.obj
	@echo ... supplystation.i
	@echo ... supplystation.s
	@echo ... teamplay.obj
	@echo ... teamplay.i
	@echo ... teamplay.s
	@echo ... totems.obj
	@echo ... totems.i
	@echo ... totems.s
	@echo ... trade.obj
	@echo ... trade.i
	@echo ... trade.s
	@echo ... upgrades.obj
	@echo ... upgrades.i
	@echo ... upgrades.s
	@echo ... v_abilitylist.obj
	@echo ... v_abilitylist.i
	@echo ... v_abilitylist.s
	@echo ... v_autobind.obj
	@echo ... v_autobind.i
	@echo ... v_autobind.s
	@echo ... v_cmd.obj
	@echo ... v_cmd.i
	@echo ... v_cmd.s
	@echo ... v_file_IO.obj
	@echo ... v_file_IO.i
	@echo ... v_file_IO.s
	@echo ... v_hw.obj
	@echo ... v_hw.i
	@echo ... v_hw.s
	@echo ... v_items.obj
	@echo ... v_items.i
	@echo ... v_items.s
	@echo ... v_luasettings.obj
	@echo ... v_luasettings.i
	@echo ... v_luasettings.s
	@echo ... v_maplist.obj
	@echo ... v_maplist.i
	@echo ... v_maplist.s
	@echo ... v_mysql_gds.obj
	@echo ... v_mysql_gds.i
	@echo ... v_mysql_gds.s
	@echo ... v_sqlite_character.obj
	@echo ... v_sqlite_character.i
	@echo ... v_sqlite_character.s
	@echo ... v_sqlite_unidb.obj
	@echo ... v_sqlite_unidb.i
	@echo ... v_sqlite_unidb.s
	@echo ... v_tbi.obj
	@echo ... v_tbi.i
	@echo ... v_tbi.s
	@echo ... v_utils.obj
	@echo ... v_utils.i
	@echo ... v_utils.s
	@echo ... vote.obj
	@echo ... vote.i
	@echo ... vote.s
	@echo ... weapon_upgrades.obj
	@echo ... weapon_upgrades.i
	@echo ... weapon_upgrades.s
	@echo ... weapons.obj
	@echo ... weapons.i
	@echo ... weapons.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

